title: ProofFrog
description: A tool for verifying game-hopping proofs
theme: just-the-docs

url: https://prooffrog.github.io

aux_links:
  ProofFrog GitHub: https://github.com/ProofFrog

plugins:
  - jekyll-katex

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
